### ISSUE TITLE
Add ID prefix listing to config files

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/koza#58]
We need to document which prefixes we expect for each entity type generated. At a minimum, this should look like 

```
entity_types:
    biolink:Gene
        id_prefix: 
            - 'MGI'
            - 'Xenbase'
            - 
    biolink:PhenotypicFeature
        id_prefix:
            - 'MP'
            - 'XPO'
```

Taking it a step further, we could replace the lists of node and edge properties and specifying all of the properties in this same structure. It's a little repetitive, but offers the chance for an extra layer of validation if a property is set in the python code that wasn't configured in the yaml. 

```
entities:
    biolink:Gene:
        id_prefix: 
            - 'MGI'
            - 'Xenbase'
        properties:
            - 'id'
            - 'category'
            - 'provided_by'
    'biolink:PhenotypicFeature':
        id_prefix:
            - 'MP'
            - 'XPO'
        properties:
            - 'id'
            - 'category'
            - 'provided_by'    
    'biolink:GeneToPhenotypicFeatureAssociation':
        id_prefix:
            - 'uuid'
        properties:
            - 'id'
            - 'subject'
            - 'predicate'
            - 'object'
            - 'category'
            - 'relation'
            - 'qualifiers'
            - 'publications'
            - 'provided_by'   
```
